#include <thread>                                                                                                                                                                                                                   
#include <queue>                                                                                                                                                                                                                    
#include <mutex>                                                                                                                                                                                                                    
#include <condition_variable>                                                                                                                                                                                                       
#include <iostream>                                                                                                                                                                                                                 
#include <chrono>                                                                                                                                                                                                                   
#include <fstream>                                                                                                                                                                                                                  
#include <future>                                                                                                                                                                                                                   
#include <sstream>                                                                                                                                                                                                                  
                                                                                                                                                                                                                                    
void ReadFromFile(const std::string & file_path, std::promise<std::string> & promise) {                                                                                                                                             
  std::ostringstream oss;                                                                                                                                                                                                           
  std::ifstream my_file(file_path);                                                                                                                                                                                                 
  if (my_file.is_open()) {                                                                                                                                                                                                          
    std::string line("");                                                                                                                                                                                                           
    while (getline(my_file,line)) {                                                                                                                                                                                                 
      oss << line;                                                                                                                                                                                                                  
    }                                                                                                                                                                                                                               
    my_file.close();                                                                                                                                                                                                                
  }                                                                                                                                                                                                                                 
  std::cout << "Value are ready" << std::endl;                                                                                                                                                                                    
  std::this_thread::sleep_for (std::chrono::seconds(1));                                                                                                                                                                            
  promise.set_value(oss.str());                                                                                                                                                                                                     
}           

void PrintNumber() {                                                                                                                                                                                                                
  std::promise<std::string> read_file_promise;                                                                                                                                                                                      
  std::future<std::string> read_file_future = read_file_promise.get_future();                                                                                                                                                       
  std::thread t2(ReadFromFile, "./test.txt", std::ref(read_file_promise));                                                                                                                                                          
                                                                                                                                                                                                                                    
  t2.detach();                                                                                                                                                                                                                      
  for (std::size_t i=0; i<1000; ++i) {                                                                                                                                                                                              
    std::cout << i << std::endl;                                                                                                                                                                                                    
  }                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                    
  std::string & reval = read_file_future.get();                                                                                                                                                                                     
}                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                    
void Test() {                                                                                                                                                                                                                       
  std::thread t1(PrintNumber);                                                                                                                                                                                                      
  t1.join();                                                                                                                                                                                                                        
}                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                    
int main() {                                                                                                                                                                                                                        
  std::chrono::high_resolution_clock::time_point t1 = std::chrono::high_resolution_clock::now();                                                                                                                                    
  Test();                                                                                                                                                                                                                           
  std::chrono::high_resolution_clock::time_point t2 = std::chrono::high_resolution_clock::now();                                                                                                                                    
  auto duration = std::chrono::duration_cast<std::chrono::microseconds>( t2 - t1 ).count();                                                                                                                                         
  std::cout << "Running time : " << duration << std::endl;                                                                                                                                                                          
  return 0;                                                                                                                                                                                                                         
}         
